lectia-3: add gradients and filters
CiochinaAndrei/css-advanced pull request #2
Opened 2023-03-19 21:15 UTC by CiochinaAndrei

2023-03-19 21:21 UTC, alexcracea requested changes

2023-03-19 21:21 UTC, alexcracea commented on scss/main.scss
> +@import 'components/fonts';
please remove reduntant fonts importing

2023-03-19 21:21 UTC, alexcracea commented on index.html
> +      <div class="section" id="gradients">
please add link to `#gradients` into the aside menu as well

2023-03-20 11:25 UTC, CiochinaAndrei commented
Hello Alex please review it now. Thanks

2023-03-20 11:28 UTC, alexcracea approved these changes

2023-03-20 11:28 UTC, merged