lectia-5: add transform-properties & Desantro
CiochinaAndrei/css-advanced pull request #4
Opened 2023-03-28 07:58 UTC by CiochinaAndrei

La Box nu am putut adaiga JS, este exact ca la cube... si nu lucreaza

2023-03-30 12:40 UTC, alexcracea requested changes

2023-03-30 12:40 UTC, alexcracea commented on scss/components/_fonts.scss
> +      url('components/Myriad-pro/MyriadPro-Semibold.svg#MyriadPro-Semibold') format('svg');
this structure should be different, please place `Myriad-Pro` fonts under `fonts/` folder in the root of the project, it shouldn't be part of `scss/`. Here in the url you should import them as if you're importing them from final .css file - `../fonts/<font file>`

2023-03-30 17:50 UTC, CiochinaAndrei commented on scss/components/_fonts.scss
> +      url('components/Myriad-pro/MyriadPro-Semibold.svg#MyriadPro-Semibold') format('svg');
changed them, and added lesson-6

2023-03-31 07:31 UTC, alexcracea approved these changes

2023-03-31 07:31 UTC, merged